core_homepage:
    path:     /
    defaults:
        _controller: CoreBundle:Default:show
        slug: accueil

core_adminpage:
    path:     /admin
    defaults: { _controller: CoreBundle:Default:admin }

# requètes ajax
ajax_snippet_image_send:
    path:     /ajax/snippet/image/send/{id}
    defaults: { _controller: CoreBundle:Galery:ajaxSnippetImageSend }

ajax_select_img:
    path:     /ajax/select/img/{id}
    defaults: { _controller: CoreBundle:Galery:ajaxSelectImg }

ajax_add_galery_user:
    path:     /ajax/add/user/galery/{galery}/{user}
    defaults: { _controller: CoreBundle:Galery:ajaxAddGaleryUser }

# Gestion du menu
add_link:
    path:     /admin/addlink
    defaults: { _controller: CoreBundle:Menu:add }

edit_link:
    path:     /admin/editlink/{id}
    defaults: { _controller: CoreBundle:Menu:edit }
    requirements:
        id: \d+

delete_link:
    path:     /admin/dellink/{id}
    defaults: { _controller: CoreBundle:Menu:delete }
    requirements:
        id: \d+

up_link:
    path:     /admin/uplink/{id}
    defaults: { _controller: CoreBundle:Menu:upLink }
    requirements:
        id: \d+

down_link:
    path:     /admin/downlink/{id}
    defaults: { _controller: CoreBundle:Menu:downLink }
    requirements:
        id: \d+

# Gestion des pages
add_page:
    path:     /admin/ajouter
    defaults: { _controller: CoreBundle:Default:add }

edit_page:
    path:     /admin/editer/{id}
    defaults: { _controller: CoreBundle:Default:edit }
    requirements:
        id: \d+

delete_page:
    path:     /admin/delete/{id}
    defaults: { _controller: CoreBundle:Default:delete }
    requirements:
        id: \d+

# Gestion des galeries
galery_view:
    path:     /galery/{id}
    defaults: { _controller: CoreBundle:Galery:view }
    requirements:
        id: \d+

private_galery:
    path:     /private/{id}
    defaults: { _controller: CoreBundle:Galery:privateGalery }
    requirements:
            id: \d+

shootings:
    path:     /shootings
    defaults: { _controller: CoreBundle:Galery:shootings }

add_galery:
    path:     /admin/addgalery
    defaults: { _controller: CoreBundle:Galery:add }

edit_galery:
    path:     /admin/editg/{id}
    defaults: { _controller: CoreBundle:Galery:edit }
    requirements:
        id: \d+

delete_galery:
    path:     /admin/deleteg/{id}
    defaults: { _controller: CoreBundle:Galery:delete }
    requirements:
        id: \d+

delete_image:
    path:     /admin/deleteimg/{id}
    defaults: { _controller: CoreBundle:Galery:deleteImg }
    requirements:
        id: \d+

show_page:
    path:    /{slug}
    defaults:
        _controller: CoreBundle:Default:show
