user_index:
    path:     /
    defaults: { _controller: "CoreBundle:UserAdmin:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "CoreBundle:UserAdmin:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "CoreBundle:UserAdmin:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoreBundle:UserAdmin:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoreBundle:UserAdmin:delete" }
    methods:  DELETE
