<?php

namespace CoreBundle\Repository;

/**
 * LienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbLiens(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(l) FROM CoreBundle:Lien l WHERE l.ordre != \'null\''
            )
            ->getResult()
            ;
    }
}
